.TH "ktxsc" 1 "Tue Apr 20 2021" "Version 4.0.0" "Khronos Texture Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ktxsc \- Supercompress the images in a KTX2 file\&.
.SH "SYNOPSIS"
.PP
ktxsc [options] [\fIinfile\fP \&.\&.\&.]
.SH "DESCRIPTION"
.PP
\fBktxsc\fP can encode and supercompresses the images in Khronos texture format version 2 files (KTX2) \&. Uncompressed files, i\&.e those whose vkFormat name does not end in \fC_BLOCK\fP can be encoded to Basis Universal (encoded to ETC1S then supercompressed with an integrated LZ step), encoded to UASTC or supercompressed with Zstandard (zstd)\&. Any image format, except Basis Universal, can be supercompressed with zstd\&. For best results with UASTC, the data should be conditioned for zstd by using the \fI--uastc_rdo_q\fP and, optionally, \fI--uastc_rdo_d\fP options\&.
.PP
\fBktxsc\fP reads each named \fIinfile\fP and compresses it in place\&. When \fIinfile\fP is not specified, a single file will be read from \fIstdin\fP\&. and the output written to \fIstdout\fP\&. When one or more files is specified each will be compressed in place\&.
.PP
The following options are available: 
.IP "\fB-o outfile, --output=outfile \fP" 1c
Write the output to \fIoutfile\fP\&. If \fIoutfile\fP is 'stdout', output will be written to stdout\&. If there is more than 1 \fIinfile\fP the command prints its usage message and exits\&. 
.IP "\fB-f, --force \fP" 1c
If the destination file cannot be opened, remove it and create a new file, without prompting for confirmation regardless of its permissions\&. 
.IP "\fB--t2 \fP" 1c
Output a KTX version2 file\&. Always true\&. 
.PP
.IP "\fB--bcmp \fP" 1c
Supercompress the image data with ETC1S / BasisLZ\&. Implies \fB--t2\fP\&. RED images will become RGB with RED in each component\&. RG images will have R in the RGB part and G in the alpha part of the compressed texture\&. When set, the following BasisLZ-related options become valid otherwise they are ignored\&. 
.IP "\fB--no_multithreading \fP" 1c
Disable multithreading\&. Deprecated\&. For backward compatibility only\&. Use \fB--threads\fP 1 instead\&. 
.IP "\fB--threads <count> \fP" 1c
Explicitly set the number of threads to use during compression\&. By default, ETC1S / BasisLZ compression will use the number of threads reported by \fCthread::hardware_concurrency\fP or 1 if value returned is 0\&. 
.IP "\fB--clevel <level> \fP" 1c
ETC1S / BasisLZ compression level, an encoding speed vs\&. quality tradeoff\&. Range is [0,5], default is 1\&. Higher values are slower, but give higher quality\&. 
.IP "\fB--qlevel <level> \fP" 1c
ETC1S / BasisLZ quality level\&. Range is [1,255]\&. Lower gives better compression/lower quality/faster\&. Higher gives less compression /higher quality/slower\&. \fB--qlevel\fP automatically determines values for \fB--max_endpoints\fP, \fB--max-selectors\fP, \fB--endpoint_rdo_threshold\fP and \fB--selector_rdo_threshold\fP for the target quality level\&. Setting these options overrides the values determined by \fB--qlevel\fP which defaults to 128 if neither it nor both of \fB--max_endpoints\fP and \fB--max_selectors\fP have been set\&.
.PP
\fBNote\fP
.RS 4
Both of \fB--max_endpoints\fP and \fB--max_selectors\fP must be set for them to have any effect\&. If all three options are set, a warning will be issued that \fB--qlevel\fP will be ignored\&. 
.PP
\fB--qlevel\fP will only determine values for \fB--endpoint_rdo_threshold\fP and \fB--selector_rdo_threshold\fP when its value exceeds 128, otherwise their defaults will be used\&. 
.RE
.PP
.IP "\fB--max_endpoints <arg> \fP" 1c
Manually set the maximum number of color endpoint clusters\&. Range is [1,16128]\&. Default is 0, unset\&. If this is set, \fB--max_selectors\fP must also be set, otherwise the value will be ignored\&. 
.IP "\fB--endpoint_rdo_threshold <arg> \fP" 1c
Set endpoint RDO quality threshold\&. The default is 1\&.25\&. Lower is higher quality but less quality per output bit (try [1\&.0,3\&.0])\&. This will override the value chosen by \fB--qlevel\fP\&. 
.IP "\fB--max_selectors <arg> \fP" 1c
Manually set the maximum number of color selector clusters\&. Range is [1,16128]\&. Default is 0, unset\&. If this is set, \fB--max_selectors\fP must also be set, otherwise the value will be ignored\&. 
.IP "\fB--selector_rdo_threshold <arg> \fP" 1c
Set selector RDO quality threshold\&. The default is 1\&.5\&. Lower is higher quality but less quality per output bit (try [1\&.0,3\&.0]\&. This will override the value chosen by \fB--qlevel\fP\&. 
.IP "\fB--normal_map \fP" 1c
Tunes codec parameters for better quality on normal maps (no selector RDO, no endpoint RDO)\&. Only valid for linear textures\&. 
.IP "\fB--separate_rg_to_color_alpha \fP" 1c
Separates the input R and G channels to RGB and A (for tangent space XY normal maps)\&. Only needed with 3 or 4 component input images\&. 
.IP "\fB--no_endpoint_rdo \fP" 1c
Disable endpoint rate distortion optimizations\&. Slightly faster, less noisy output, but lower quality per output bit\&. Default is to do endpoint RDO\&. 
.IP "\fB--no_selector_rdo \fP" 1c
Disable selector rate distortion optimizations\&. Slightly faster, less noisy output, but lower quality per output bit\&. Default is to do selector RDO\&. 
.PP
.IP "\fB--uastc [<level>] \fP" 1c
Create a texture in high-quality transcodable UASTC format\&. Implies \fB--t2\fP\&. The optional parameter \fIlevel\fP selects a speed vs quality tradeoff as shown in the following table:
.PP
Level Speed Quality 0 Fastest 43\&.45dB 1 Faster 46\&.49dB 2 Default 47\&.47dB 3 Slower 48\&.01dB 4 Very slow 48\&.24dB 
.PP
You are strongly encouraged to also specify \fB--zcmp\fP to losslessly compress the UASTC data\&. This and any LZ-style compression can be made more effective by conditioning the UASTC texture data using the Rate Distortion Optimization (RDO) post-process stage\&. When \fB--uastc\fP is set the following options become available for controlling RDO: 
.IP "\fB--uastc_rdo_l [<lambda>] \fP" 1c
Enable UASTC RDO post-processing and optionally set UASTC RDO quality scalar (lambda) to \fIlambda\fP\&. Lower values yield higher quality/larger LZ compressed files, higher values yield lower quality/smaller LZ compressed files\&. A good range to try is [\&.25,10]\&. For normal maps a good range is [\&.25-\&.75]\&. The full range is [\&.001,10\&.0]\&. Default is 1\&.0\&.
.PP
\fBNote\fP
.RS 4
Previous versions used the \fB--uastc_rdo_q\fP option which was removed because the RDO algorithm changed\&. 
.RE
.PP
.IP "\fB--uastc_rdo_d <dictsize> \fP" 1c
Set UASTC RDO dictionary size in bytes\&. Default is 4096\&. Lower values=faster, but give less compression\&. Range is [64,65536]\&. 
.IP "\fB--uastc_rdo_b <scale> \fP" 1c
Set UASTC RDO max smooth block error scale\&. Range is [1\&.0,300\&.0]\&. Default is 10\&.0, 1\&.0 is disabled\&. Larger values suppress more artifacts (and allocate more bits) on smooth blocks\&. 
.IP "\fB--uastc_rdo_s <deviation> \fP" 1c
Set UASTC RDO max smooth block standard deviation\&. Range is [\&.01,65536\&.0]\&. Default is 18\&.0\&. Larger values expand the range of blocks considered smooth\&. 
.IP "\fB--uastc_rdo_f \fP" 1c
Do not favor simpler UASTC modes in RDO mode\&. 
.IP "\fB--uastc_rdo_m \fP" 1c
Disable RDO multithreading (slightly higher compression, deterministic)\&. 
.PP
.IP "\fB--no_sse \fP" 1c
Forbid use of the SSE instruction set\&. Ignored if CPU does not support SSE\&. Only the Basis Universal compressor uses SSE\&. 
.IP "\fB--verbose \fP" 1c
Print encoder/compressor activity status to stdout\&. Currently only the Basis Universal compressor emits status\&. 
.IP "\fB--zcmp [<compressionLevel>] \fP" 1c
Supercompress the data with Zstandard\&. Implies \fB--t2\fP\&. Can be used with data in any format except ETC1S / BasisLZ (\fB--bcmp\fP)\&. Most effective with RDO-conditioned UASTC or uncompressed formats\&. The optional \fIcompressionLevel\fP range is 1 - 22 and the default is 3\&. Lower values=faster but give less compression\&. Values above 20 should be used with caution as they require more memory\&. 
.PP
.IP "\fB--help \fP" 1c
Print this usage message and exit\&. 
.IP "\fB--version \fP" 1c
Print the version number of this program and exit\&. 
.PP
 In case of ambiguity, such as when the last option is one with an optional parameter, separate options from file names with ' -- '\&.
.PP
Any specified ETC1S / BasisLZ and supercompression options are recorded in the metadata item \fCKTXwriterScParams\fP in the output file\&.  
.SH "EXIT STATUS"
.PP
\fBtoktx\fP exits 0 on success, 1 on command line errors and 2 on functional errors\&.
.SH "HISTORY"
.PP
\fBVersion 4\&.0\fP
.RS 4

.IP "\(bu" 2
Initial version\&.
.PP
.RE
.PP
.SH "AUTHOR"
.PP
Mark Callow, Edgewise Consulting www\&.edgewise-consulting\&.com 
